version: 2
jobs:
  build:
    docker:
      - image: danieluranga/leela_chess_zero-lc0_ubuntu_builder:0.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: CC=clang-6.0 CXX=clang++-6.0 ./build.sh
      - run:
          command: cp build/release/lc0 /tmp/lc0
      - store_artifacts:
          path: /tmp/lc0
          destination: lc0-ubuntu-18-04
