version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Install APT dependencies
          command: sudo apt-get install clang-6.0 ninja-build python3-pip nvidia-opencl-dev libopenblas-dev libboost-dev nvidia-cuda-dev nvidia-cuda-toolkit
      - run:
          name: Install Python dependencies
          command: sudo -H pip3 install meson
      - run:
          name: Install Intel Math Kernel Library
          command: wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list' && sudo apt-get update && sudo apt-get install intel-mkl-64bit-2018.2-046
      - run:
          name: (Workaround) Create a symlink for the OpenBlas include files
          command: sudo ln -s /usr/include/ /usr/include/openblas
      - run:
          name: Build
          command: CC=clang-6.0 CXX=clang++-6.0 ./build.sh
      - run:
          command: cp build/release/lc0 /tmp/lc0
      - store_artifacts:
          path: /tmp/lc0
          destination: lc0-ubuntu-18-04
