version: 2
jobs:
  build:
    docker:
      - image: danieluranga/leela_chess_zero-lc0_ubuntu_builder:0.0.8
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Update Meson
          command: pip3 install --upgrade meson==0.58.1
      - run:
          name: Meson GCC
          environment:
            CC: gcc-8
            CXX: g++-8
          command: meson build-gcc -Dgtest=false
      - run:
          name: Build GCC
          command: |
            cd build-gcc
            ninja
  "mac":
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Install build tools
          command: |
            pip install meson==0.63
            pip install ninja
            brew install ispc
      - run:
          name: Build lc0
          command: |
            meson build --buildtype=release -Dgtest=false -Dopencl=false
            cd build
            ninja
      - run:
          command: cp build/lc0 /tmp/lc0
      - store_artifacts:
          path: /tmp/lc0
          destination: lc0-metal-macos-12.3.1
workflows:
  version: 2
  builds:
    jobs:
      - build
      - "mac"
